<?php  $db_data["theme"] = array (
  0 => 
  array (
    'name' => 'Flowing_Dark',
    'color_map' => '3',
    'logo_path' => 'res/logo.png',
    'logo_style' => 'file',
    'logo_text' => 'phpAlbum.net',
    'directory_style' => 'flowing',
    'additional_thmb_height' => '65',
    'additional_thmb_width' => '45',
    'maximum_photos_per_page' => '100',
    'raster_dir_x' => '4',
    'raster_dir_y' => '3',
    'disable_bottom_nextprev' => 'false',
    'show_filenames' => 'true',
    'display_shadows' => 'true',
    'picture_border_size' => '10',
    'thumbnail_border_size' => '5',
    'dir_logo_style' => 'pic_thmb_size',
    'dir_logo_size' => '70',
    'dir_logo_quality' => '85',
    'dir_logo_square_thumbnail' => 'false',
    'show_search_box' => 'true',
  ),
  1 => 
  array (
    'name' => 'Borders',
    'color_map' => '1',
    'logo_path' => 'res/logo.png',
    'logo_style' => 'file',
    'logo_text' => 'phpAlbum.net',
    'directory_style' => 'flowing',
    'additional_thmb_height' => '65',
    'additional_thmb_width' => '45',
    'maximum_photos_per_page' => '100',
    'raster_dir_x' => '4',
    'raster_dir_y' => '3',
    'disable_bottom_nextprev' => 'false',
    'show_filenames' => 'true',
    'display_shadows' => 'true',
    'picture_border_size' => '10',
    'thumbnail_border_size' => '5',
    'dir_logo_style' => 'pic_other_size',
    'dir_logo_size' => '70',
    'dir_logo_quality' => '85',
    'dir_logo_square_thumbnail' => 'false',
    'show_search_box' => 'true',
  ),
);